"""OKF v0.2 conformance: the required `type`, the §8 index, and the lint check."""
from cortex import cli


# ---- §11: type is required on knowledge ----

def test_new_knowledge_without_type_errors(kbhome, capsys):
    rc = cli.main(["kb", "new", "knowledge", "untyped", "--body", "b",
                   "--description", "d"])
    assert rc == 1
    msg = capsys.readouterr().err
    assert "--type" in msg
    for canonical in ("Decision", "Reference", "Runbook", "Comparison"):
        assert canonical in msg                     # the error names the vocabulary
    assert not (kbhome / ".cortex/workspaces/ws-a/knowledge/untyped.md").exists()


def test_new_knowledge_with_blank_type_errors(kbhome):
    assert cli.main(["kb", "new", "knowledge", "blank",
                     "--type", "   ", "--body", "b"]) == 1


def test_new_knowledge_with_type_succeeds(kbhome):
    assert cli.main(["kb", "new", "knowledge", "typed",
                     "--type", "Decision", "--body", "b"]) == 0
    doc = kbhome / ".cortex/workspaces/ws-a/knowledge/typed.md"
    assert "type: Decision" in doc.read_text()


def test_new_knowledge_accepts_a_custom_type(kbhome):
    # The vocabulary is a convention, not an enum: a value outside it is fine.
    assert cli.main(["kb", "new", "knowledge", "custom",
                     "--type", "Postmortem", "--body", "b"]) == 0


def test_new_workbench_still_allows_no_type(kbhome):
    # Session-scoped, dies with the session, never part of an exported bundle.
    assert cli.main(["kb", "new", "workbench", "scratch", "--body", "b"]) == 0
    doc = kbhome / ".cortex/workspaces/ws-a/sessions/sess-a/workbench/scratch.md"
    assert "type:" not in doc.read_text()


def test_update_does_not_require_type(kbhome):
    # `update` is modify-only, and a store predating this rule still has
    # untyped docs; refusing to touch one would make them unfixable.
    kd = kbhome / ".cortex/workspaces/ws-a/knowledge"
    kd.mkdir(parents=True, exist_ok=True)
    (kd / "legacy.md").write_text(
        "---\nauthor: agent\ncreated: 2026-01-01\nupdated: 2026-01-01\n---\n\nb\n")
    assert cli.main(["kb", "update", "knowledge", "legacy",
                     "--description", "now described"]) == 0


# ---- §8: the derived index ----

def _mk(kbhome, slug, typ, desc, title=""):
    kd = kbhome / ".cortex/workspaces/ws-a/knowledge"
    kd.mkdir(parents=True, exist_ok=True)
    head = f"title: {title}\n" if title else ""
    (kd / f"{slug}.md").write_text(
        f"---\n{head}type: {typ}\nauthor: agent\ncreated: 2026-01-01\n"
        f"updated: 2026-01-01\ndescription: {desc}\n---\n\nbody\n")


def test_index_write_lands_on_lowercase_index_md(kbhome):
    _mk(kbhome, "apple", "Decision", "a decision")
    assert cli.main(["kb", "index", "--workspace", "ws-a", "--write"]) == 0
    kd = kbhome / ".cortex/workspaces/ws-a/knowledge"
    assert (kd / "index.md").is_file()
    assert not (kd / "INDEX.md").exists()


def test_index_write_emits_okf_section_8_entries(kbhome):
    _mk(kbhome, "apple", "Decision", "a decision", title="Apple Title")
    _mk(kbhome, "deploy", "Runbook", "prod release")
    cli.main(["kb", "index", "--workspace", "ws-a", "--write"])
    text = (kbhome / ".cortex/workspaces/ws-a/knowledge/index.md").read_text()
    assert "generated by cortex kb index; do not edit" in text
    assert "# Knowledge index" in text
    assert "## Decision" in text and "## Runbook" in text
    assert "* [Apple Title](apple.md) - a decision" in text
    assert "* [deploy](deploy.md) - prod release" in text     # no title -> slug
    assert text.index("## Decision") < text.index("## Runbook")


def test_index_write_groups_untyped_last(kbhome):
    _mk(kbhome, "apple", "Decision", "a decision")
    kd = kbhome / ".cortex/workspaces/ws-a/knowledge"
    (kd / "plain.md").write_text(
        "---\nauthor: agent\ncreated: 2026-01-01\nupdated: 2026-01-01\n---\n\nb\n")
    cli.main(["kb", "index", "--workspace", "ws-a", "--write"])
    text = (kd / "index.md").read_text()
    assert "## (untyped)" in text
    assert text.index("## Decision") < text.index("## (untyped)")
    assert "* [plain](plain.md) - (no description)" in text


def test_index_write_retires_a_legacy_uppercase_index(kbhome):
    _mk(kbhome, "apple", "Decision", "a decision")
    kd = kbhome / ".cortex/workspaces/ws-a/knowledge"
    (kd / "INDEX.md").write_text("stale\n")
    cli.main(["kb", "index", "--workspace", "ws-a", "--write"])
    assert not (kd / "INDEX.md").exists()
    assert "* [apple](apple.md) - a decision" in (kd / "index.md").read_text()


def test_index_write_never_indexes_itself(kbhome):
    _mk(kbhome, "apple", "Decision", "a decision")
    cli.main(["kb", "index", "--workspace", "ws-a", "--write"])
    cli.main(["kb", "index", "--workspace", "ws-a", "--write"])      # twice
    text = (kbhome / ".cortex/workspaces/ws-a/knowledge/index.md").read_text()
    assert "index.md)" not in text.replace("* [apple](apple.md)", "")


def test_index_stdout_form_is_unchanged(kbhome, capsys):
    # The flat listing is what an agent reads and what `inject` emits; §8 is
    # the file a bundle consumer parses. Changing both would move the
    # injection block for no OKF benefit.
    _mk(kbhome, "apple", "Decision", "a decision")
    cli.main(["kb", "index", "--workspace", "ws-a"])
    out = capsys.readouterr().out
    assert "## knowledge" in out
    assert "apple [Decision] - a decision" in out


def _mk_ws(kbhome, ws, slug, typ, desc):
    kd = kbhome / ".cortex/workspaces" / ws / "knowledge"
    kd.mkdir(parents=True, exist_ok=True)
    (kd / f"{slug}.md").write_text(
        f"---\ntype: {typ}\nauthor: agent\ncreated: 2026-01-01\n"
        f"updated: 2026-01-01\ndescription: {desc}\n---\n\nbody\n")


def test_root_index_write_is_section_8_with_resolvable_links(kbhome):
    _mk_ws(kbhome, "ws-a", "authn", "Decision", "why we pin v2")
    _mk_ws(kbhome, "ws-b", "authn", "Decision", "b's own auth")
    assert cli.main(["kb", "index", "--workspace", "all", "--write"]) == 0
    root_kdir = kbhome / ".cortex/knowledge"
    assert (root_kdir / "index.md").is_file()
    assert not (root_kdir / "INDEX.md").exists()
    text = (root_kdir / "index.md").read_text()
    assert "generated by cortex kb index --workspace=all" in text
    assert "# Knowledge index (all workspaces)" in text
    assert "## Decision" in text
    assert "* [authn (ws-a)](../workspaces/ws-a/knowledge/authn.md) - why we pin v2" in text
    assert "* [authn (ws-b)](../workspaces/ws-b/knowledge/authn.md) - b's own auth" in text
    # The relative URL resolves from the file that carries it.
    target = (root_kdir / "../workspaces/ws-a/knowledge/authn.md").resolve()
    assert target.is_file()


def test_root_index_retires_a_legacy_uppercase_index(kbhome):
    _mk_ws(kbhome, "ws-a", "authn", "Decision", "d")
    root_kdir = kbhome / ".cortex/knowledge"
    root_kdir.mkdir(parents=True)
    (root_kdir / "INDEX.md").write_text("stale\n")
    cli.main(["kb", "index", "--workspace", "all", "--write"])
    assert not (root_kdir / "INDEX.md").exists()


# ---- the lint check ----

def _lint(args):
    return cli.main(["kb", "lint"] + args)


def test_lint_okf_reports_untyped_knowledge_with_a_worklist_detail(kbhome, capsys):
    kd = kbhome / ".cortex/workspaces/ws-a/knowledge"
    kd.mkdir(parents=True, exist_ok=True)
    (kd / "bare.md").write_text(
        "---\ntitle: Bare Note\nauthor: agent\ncreated: 2026-01-01\n"
        "updated: 2026-01-01\ndescription: what it is about\n---\n\nb\n")
    _lint(["--workspace", "ws-a", "--check", "okf"])
    out = capsys.readouterr().out
    assert "## okf" in out
    assert "ws-a/knowledge/bare" in out
    assert "no type" in out
    # The finding doubles as the backfill worklist: enough to choose a value.
    assert "Bare Note" in out and "what it is about" in out


def test_lint_okf_is_silent_when_every_doc_is_typed(kbhome, capsys):
    _mk(kbhome, "apple", "Decision", "a decision")
    _lint(["--workspace", "ws-a", "--check", "okf"])
    out = capsys.readouterr().out
    assert "## okf" not in out
    assert "no findings" in out


def test_lint_okf_ignores_workbench(kbhome, capsys):
    wb = kbhome / ".cortex/workspaces/ws-a/sessions/sess-a/workbench"
    (wb / "draft.md").write_text(
        "---\nauthor: agent\ncreated: 2026-01-01\nupdated: 2026-01-01\n---\n\nb\n")
    # An untyped knowledge doc in the same run, so a silent check cannot pass
    # this test by reporting nothing at all.
    kd = kbhome / ".cortex/workspaces/ws-a/knowledge"
    kd.mkdir(parents=True, exist_ok=True)
    (kd / "bare.md").write_text(
        "---\nauthor: agent\ncreated: 2026-01-01\nupdated: 2026-01-01\n---\n\nb\n")
    _lint(["--workspace", "ws-a", "--check", "okf"])
    out = capsys.readouterr().out
    assert "ws-a/knowledge/bare" in out
    assert "workbench/draft" not in out


def test_lint_okf_flags_a_legacy_uppercase_index(kbhome, capsys):
    _mk(kbhome, "apple", "Decision", "a decision")
    kd = kbhome / ".cortex/workspaces/ws-a/knowledge"
    (kd / "INDEX.md").write_text("stale\n")
    _lint(["--workspace", "ws-a", "--check", "okf"])
    out = capsys.readouterr().out
    assert "INDEX.md" in out
    assert "cortex kb index --write" in out


def test_lint_okf_flags_a_hand_edited_index(kbhome, capsys):
    _mk(kbhome, "apple", "Decision", "a decision")
    kd = kbhome / ".cortex/workspaces/ws-a/knowledge"
    (kd / "index.md").write_text("# Knowledge index\n\n## Decision\n\napple - a decision\n")
    _lint(["--workspace", "ws-a", "--check", "okf"])
    out = capsys.readouterr().out
    assert "index.md" in out and "8" in out


def test_lint_okf_accepts_the_index_it_generates(kbhome, capsys):
    _mk(kbhome, "apple", "Decision", "a decision")
    cli.main(["kb", "index", "--workspace", "ws-a", "--write"])
    capsys.readouterr()
    _lint(["--workspace", "ws-a", "--check", "okf"])
    assert "no findings" in capsys.readouterr().out


def test_lint_okf_counts_toward_strict(kbhome, capsys):
    kd = kbhome / ".cortex/workspaces/ws-a/knowledge"
    kd.mkdir(parents=True, exist_ok=True)
    (kd / "bare.md").write_text(
        "---\nauthor: agent\ncreated: 2026-01-01\nupdated: 2026-01-01\n---\n\nb\n")
    assert _lint(["--workspace", "ws-a", "--check", "okf", "--strict"]) == 1


def test_lint_okf_is_selectable_by_name(kbhome, capsys):
    _mk(kbhome, "apple", "Decision", "a decision")
    assert _lint(["--workspace", "ws-a", "--check", "no-such-check"]) == 2
    assert "okf" in capsys.readouterr().err          # listed among the choices


def test_lint_runs_okf_by_default(kbhome, capsys):
    kd = kbhome / ".cortex/workspaces/ws-a/knowledge"
    kd.mkdir(parents=True, exist_ok=True)
    (kd / "bare.md").write_text(
        "---\nauthor: agent\ncreated: 2026-01-01\nupdated: 2026-01-01\n---\n\nb\n")
    _lint(["--workspace", "ws-a"])
    assert "## okf" in capsys.readouterr().out
