from cortex import cli


def _mk(kbhome, slug, typ, desc):
    kd = kbhome / ".work/workspaces/ws-a/knowledge"
    kd.mkdir(parents=True, exist_ok=True)
    (kd / f"{slug}.md").write_text(
        f"---\ntype: {typ}\nauthor: agent\ncreated: 2026-01-01\n"
        f"updated: 2026-01-01\ndescription: {desc}\n---\n\nbody\n")


def _seed(kbhome):
    _mk(kbhome, "zebra", "Reference", "z ref")
    _mk(kbhome, "apple", "Decision", "a decision")
    _mk(kbhome, "mango", "Decision", "m decision")
    kd = kbhome / ".work/workspaces/ws-a/knowledge"
    (kd / "plain.md").write_text(
        "---\nauthor: agent\ncreated: 2026-01-01\nupdated: 2026-01-01\n"
        "title: Plain Title\n---\n\nbody\n")


def test_index_render_shape_and_order(kbhome, capsys):
    _seed(kbhome)
    assert cli.main(["kb", "index", "--workspace", "ws-a"]) == 0
    out = capsys.readouterr().out
    assert "## knowledge" in out
    assert "apple [Decision] - a decision" in out
    assert "plain - Plain Title" in out                       # untyped -> title fallback
    body = [ln for ln in out.splitlines() if ln and ln[0].isalpha()]
    order = [ln.split()[0] for ln in body if ln.split()[0] in
             ("apple", "mango", "zebra", "plain")]
    assert order == ["apple", "mango", "zebra", "plain"]      # type then slug; untyped last


def test_index_max_truncation_notice(kbhome, capsys):
    _seed(kbhome)
    cli.main(["kb", "index", "--workspace", "ws-a", "--max", "2"])
    assert "... 2 more (raise --max)" in capsys.readouterr().out


def test_index_write_derived_file_with_banner(kbhome, capsys):
    _seed(kbhome)
    assert cli.main(["kb", "index", "--workspace", "ws-a", "--write"]) == 0
    idx = kbhome / ".work/workspaces/ws-a/knowledge/INDEX.md"
    assert idx.is_file()
    text = idx.read_text()
    assert "generated by cortex kb index; do not edit" in text
    assert "apple [Decision] - a decision" in text


def test_index_no_active_session_still_lists_knowledge(kbhome, capsys):
    nk = kbhome / ".work/workspaces/ws-noact/knowledge"
    nk.mkdir(parents=True)
    (nk / "lone.md").write_text(
        "---\ntype: Reference\nauthor: agent\ncreated: 2026-01-01\n"
        "updated: 2026-01-01\ndescription: lonely\n---\n\nbody\n")
    assert cli.main(["kb", "index", "--workspace", "ws-noact"]) == 0
    assert "lone [Reference] - lonely" in capsys.readouterr().out
