from cortex import cli


def _mk(kbhome, slug, typ, desc):
    kd = kbhome / ".cortex/workspaces/ws-a/knowledge"
    kd.mkdir(parents=True, exist_ok=True)
    (kd / f"{slug}.md").write_text(
        f"---\ntype: {typ}\nauthor: agent\ncreated: 2026-01-01\n"
        f"updated: 2026-01-01\ndescription: {desc}\n---\n\nbody\n")


def _seed(kbhome):
    _mk(kbhome, "zebra", "Reference", "z ref")
    _mk(kbhome, "apple", "Decision", "a decision")
    _mk(kbhome, "mango", "Decision", "m decision")
    kd = kbhome / ".cortex/workspaces/ws-a/knowledge"
    (kd / "plain.md").write_text(
        "---\nauthor: agent\ncreated: 2026-01-01\nupdated: 2026-01-01\n"
        "title: Plain Title\n---\n\nbody\n")


def test_index_render_shape_and_order(kbhome, capsys):
    _seed(kbhome)
    assert cli.main(["kb", "index", "--workspace", "ws-a"]) == 0
    out = capsys.readouterr().out
    assert "## knowledge" in out
    assert "apple [Decision] - a decision" in out
    assert "plain - Plain Title" in out                       # untyped -> title fallback
    body = [ln for ln in out.splitlines() if ln and ln[0].isalpha()]
    order = [ln.split()[0] for ln in body if ln.split()[0] in
             ("apple", "mango", "zebra", "plain")]
    assert order == ["apple", "mango", "zebra", "plain"]      # type then slug; untyped last


def test_index_max_truncation_notice(kbhome, capsys):
    _seed(kbhome)
    cli.main(["kb", "index", "--workspace", "ws-a", "--max", "2"])
    assert "... 2 more (raise --max)" in capsys.readouterr().out


def test_index_write_derived_file_with_banner(kbhome, capsys):
    _seed(kbhome)
    assert cli.main(["kb", "index", "--workspace", "ws-a", "--write"]) == 0
    idx = kbhome / ".cortex/workspaces/ws-a/knowledge/INDEX.md"
    assert idx.is_file()
    text = idx.read_text()
    assert "generated by cortex kb index; do not edit" in text
    assert "apple [Decision] - a decision" in text


def test_index_no_active_session_still_lists_knowledge(kbhome, capsys):
    nk = kbhome / ".cortex/workspaces/ws-noact/knowledge"
    nk.mkdir(parents=True)
    (nk / "lone.md").write_text(
        "---\ntype: Reference\nauthor: agent\ncreated: 2026-01-01\n"
        "updated: 2026-01-01\ndescription: lonely\n---\n\nbody\n")
    assert cli.main(["kb", "index", "--workspace", "ws-noact"]) == 0
    assert "lone [Reference] - lonely" in capsys.readouterr().out


def _mk_ws(kbhome, ws, slug, typ, desc):
    kd = kbhome / ".cortex/workspaces" / ws / "knowledge"
    kd.mkdir(parents=True, exist_ok=True)
    (kd / f"{slug}.md").write_text(
        f"---\ntype: {typ}\nauthor: agent\ncreated: 2026-01-01\n"
        f"updated: 2026-01-01\ndescription: {desc}\n---\n\nbody\n")


def test_index_all_groups_by_type_and_tags_workspace(kbhome, capsys):
    _mk_ws(kbhome, "ws-a", "authn", "Decision", "why we pin v2")
    _mk_ws(kbhome, "ws-b", "deploy", "Runbook", "prod release")
    _mk_ws(kbhome, "ws-b", "authn", "Decision", "b's own auth")   # same slug, distinct
    assert cli.main(["kb", "index", "--workspace", "all"]) == 0
    out = capsys.readouterr().out
    assert "## Decision" in out and "## Runbook" in out
    assert "authn (ws-a) - why we pin v2" in out
    assert "authn (ws-b) - b's own auth" in out          # NOT merged
    assert "deploy (ws-b) - prod release" in out
    assert out.index("## Decision") < out.index("## Runbook")


def test_index_all_max_caps_per_section(kbhome, capsys):
    for i in range(5):
        _mk_ws(kbhome, "ws-a", f"d{i}", "Decision", f"n{i}")
    cli.main(["kb", "index", "--workspace", "all", "--max", "2"])
    out = capsys.readouterr().out
    assert "... 3 more (raise --max)" in out


def test_index_all_write_creates_root_index(kbhome, capsys):
    _mk_ws(kbhome, "ws-a", "authn", "Decision", "d")
    assert cli.main(["kb", "index", "--workspace", "all", "--write"]) == 0
    idx = kbhome / ".cortex/knowledge/INDEX.md"
    assert idx.is_file()
    text = idx.read_text()
    assert "generated by cortex kb index --workspace=all" in text
    assert "authn (ws-a) - d" in text


def test_index_all_type_grouping_is_case_insensitive(kbhome, capsys):
    _mk_ws(kbhome, "ws-a", "one", "API", "first")
    _mk_ws(kbhome, "ws-b", "two", "api", "second")
    cli.main(["kb", "index", "--workspace", "all"])
    out = capsys.readouterr().out
    # A single case-insensitive section holds both docs.
    assert out.count("## ") == 1
    assert "one (ws-a) - first" in out
    assert "two (ws-b) - second" in out


def test_index_all_no_description_placeholder(kbhome, capsys):
    kd = kbhome / ".cortex/workspaces/ws-a/knowledge"
    kd.mkdir(parents=True, exist_ok=True)
    (kd / "bare.md").write_text(
        "---\nauthor: agent\ncreated: 2026-01-01\nupdated: 2026-01-01\n---\n\nbody\n")
    cli.main(["kb", "index", "--workspace", "all"])
    assert "bare (ws-a) - (no description)" in capsys.readouterr().out
