#!/usr/bin/env bash
set -euo pipefail
SELF_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SELF_DIR/helpers.sh"

tmp="$(make_test_home)"
trap "cleanup_test_home $tmp" EXIT
kdir="$tmp/.work/workspaces/ws-a/knowledge"
mkdir -p "$kdir"

mk() { # slug type desc
    cat > "$kdir/$1.md" <<EOF
---
type: $2
author: agent
created: 2026-01-01
updated: 2026-01-01
description: $3
---

body
EOF
}
mk zebra Reference "z ref"
mk apple Decision "a decision"
mk mango Decision "m decision"
# untyped doc: no type field, falls back to title then placeholder
cat > "$kdir/plain.md" <<EOF
---
author: agent
created: 2026-01-01
updated: 2026-01-01
title: Plain Title
---

body
EOF

out="$(HOME="$tmp" "$BIN" index --workspace ws-a)"

# Section header present
printf '%s\n' "$out" | grep -qF "## knowledge" || { echo "FAIL: no header" >&2; exit 1; }

# Render shape: "<slug> [<type>] - <desc>"
printf '%s\n' "$out" | grep -qF "apple [Decision] - a decision" || { echo "FAIL: apple line" >&2; exit 1; }
# Untyped uses title fallback, no [type]
printf '%s\n' "$out" | grep -qF "plain - Plain Title" || { echo "FAIL: plain line" >&2; exit 1; }

# Order: within Decision, apple before mango; Decision before Reference; untyped last.
body="$(printf '%s\n' "$out" | grep -E '^[a-z]+ ')"
a_ln="$(printf '%s\n' "$body" | grep -n '^apple ' | cut -d: -f1)"
m_ln="$(printf '%s\n' "$body" | grep -n '^mango ' | cut -d: -f1)"
z_ln="$(printf '%s\n' "$body" | grep -n '^zebra ' | cut -d: -f1)"
p_ln="$(printf '%s\n' "$body" | grep -n '^plain ' | cut -d: -f1)"
[[ "$a_ln" -lt "$m_ln" && "$m_ln" -lt "$z_ln" && "$z_ln" -lt "$p_ln" ]] || { echo "FAIL: order $a_ln $m_ln $z_ln $p_ln" >&2; exit 1; }

# Bounding + truncation notice
bounded="$(HOME="$tmp" "$BIN" index --workspace ws-a --max 2)"
printf '%s\n' "$bounded" | grep -qF "... 2 more (raise --max)" || { echo "FAIL: no truncation notice" >&2; exit 1; }

# No active session (and no --session): knowledge still renders, exit 0.
# (resolve_session die()s here; index must not abort on it.) Use a pointer-less
# workspace so no .active.* resolves.
nk="$tmp/.work/workspaces/ws-noact/knowledge"; mkdir -p "$nk"
cat > "$nk/lone.md" <<EOF
---
type: Reference
author: agent
created: 2026-01-01
updated: 2026-01-01
description: lonely
---

body
EOF
noact="$(HOME="$tmp" "$BIN" index --workspace ws-noact)"; rc=$?
assert_eq 0 "$rc" "index exit with no active session"
printf '%s\n' "$noact" | grep -qF "lone [Reference] - lonely" || { echo "FAIL: no-active knowledge missing" >&2; exit 1; }

# --write produces derived INDEX.md with banner
HOME="$tmp" "$BIN" index --workspace ws-a --write >/dev/null
assert_file "$kdir/INDEX.md"
assert_contains "$kdir/INDEX.md" "generated by cortex kb index; do not edit"
assert_contains "$kdir/INDEX.md" "apple [Decision] - a decision"

echo "test_index: PASS"
