#!/usr/bin/env python3
"""One-shot migration for existing ~/.work knowledge/workbench docs.

- Normalizes frontmatter: backfills `updated` (= created) and enforces the
  canonical field order, line-preservingly (no yaml.dump / re-quoting).
- Regenerates knowledge/INDEX.md banner text to `cortex kb index`.
- Reports (does NOT edit) `work-kb`/`work-viz` references in doc prose.
Dry-run by default; --write applies frontmatter + banner edits.
"""
from __future__ import annotations
import sys, re, argparse
from pathlib import Path

# Bootstrap: this script may run standalone (python3 .../migrate_kb_frontmatter.py),
# so put the repo root (scripts -> tracking-work-kb -> skills -> root) on sys.path
# to import the cortex engine.
sys.path.insert(0, str(Path(__file__).resolve().parents[3]))

try:
    import yaml
except Exception:
    yaml = None

# Single source of truth for field order + boundary splitting: the cortex engine.
from cortex.frontmatter import CANON, split_lines
STALE = re.compile(r"\bwork-(kb|viz)\b")
_KEY = re.compile(r"^([A-Za-z_][A-Za-z0-9_]*):")

# Exact derived-INDEX banner strings (old -> new); replaced verbatim so prose
# mentions of "work-kb index" are never touched.
_OLD_BANNER = "<!-- generated by work-kb index; do not edit. regenerate with: work-kb index --write -->"
_NEW_BANNER = "<!-- generated by cortex kb index; do not edit. regenerate with: cortex kb index --write -->"


def normalize_frontmatter(text):
    """Return (new_text or None, changed). None when there is no frontmatter."""
    fm_lines, body_lines, _ = split_lines(text)
    if fm_lines is None:
        return None, False
    if yaml is not None:
        try:
            yaml.safe_load("\n".join(fm_lines))
        except Exception:
            return None, False  # malformed; skip
    # Only rewrite flat-scalar frontmatter. If any non-blank line is not a
    # "key: value" line (a YAML list item, folded/literal block, or other
    # continuation), skip rather than risk dropping structured values on
    # rebuild, since this reconstructs the block from `key:` lines only.
    for ln in fm_lines:
        if ln.strip() and not _KEY.match(ln):
            return None, False
    kv, order = {}, []
    for ln in fm_lines:
        mm = _KEY.match(ln)
        if mm:
            k = mm.group(1)
            kv[k] = ln
            if k not in order:
                order.append(k)
    if "updated" not in kv and "created" in kv:
        # Copy everything after the "created" key (the ": <value>" part) verbatim.
        kv["updated"] = "updated" + kv["created"][len("created"):]
    elif "updated" not in kv:
        return None, False  # nothing to anchor an updated to; leave alone
    new_fm = [kv[k] for k in CANON if k in kv]
    new_fm += [kv[k] for k in order if k not in CANON]  # preserve unknown keys
    if new_fm == fm_lines:
        return text, False
    new_text = "\n".join(["---"] + new_fm + ["---"] + body_lines)
    return new_text, True


def stale_refs_in_body(text):
    _, body_lines, _ = split_lines(text)
    if body_lines is None:
        body_lines = text.split("\n")
    out = []
    for i, ln in enumerate(body_lines, 1):
        if STALE.search(ln):
            out.append((i, ln))
    return out


def _iter_docs(root: Path):
    for ws in sorted(p for p in root.iterdir() if p.is_dir()):
        kd = ws / "knowledge"
        if kd.is_dir():
            yield from sorted(kd.glob("*.md"))
        sess = ws / "sessions"
        if sess.is_dir():
            for s in sorted(p for p in sess.iterdir() if p.is_dir()):
                wb = s / "workbench"
                if wb.is_dir():
                    yield from sorted(wb.glob("*.md"))


def main(argv):
    ap = argparse.ArgumentParser(prog="migrate_kb_frontmatter")
    ap.add_argument("--root", default=str(Path.home() / ".work" / "workspaces"))
    ap.add_argument("--write", action="store_true")
    args = ap.parse_args(argv)
    root = Path(args.root)
    if not root.is_dir():
        print(f"error: root not found: {root}", file=sys.stderr)
        return 1

    normalized = banners = unchanged = skipped = 0
    prose = []
    for doc in _iter_docs(root):
        text = doc.read_text(encoding="utf-8")
        if doc.name.lower() == "index.md":
            new = text.replace(_OLD_BANNER, _NEW_BANNER)
            if new != text:
                banners += 1
                if args.write:
                    doc.write_text(new, encoding="utf-8")
            continue
        new, changed = normalize_frontmatter(text)
        if changed:
            normalized += 1
            if args.write:
                doc.write_text(new, encoding="utf-8")
        elif new is None:
            skipped += 1        # no / invalid / non-flat frontmatter: left untouched
        else:
            unchanged += 1      # already current
        for lineno, line in stale_refs_in_body(text):
            prose.append((doc, lineno, line.strip()))

    mode = "wrote" if args.write else "would change (dry-run)"
    print(f"{mode}: normalized {normalized} docs, {banners} INDEX banners; "
          f"{unchanged} already current; {skipped} skipped (no/invalid frontmatter); "
          f"{len(prose)} prose references to review")
    for doc, lineno, line in prose:
        print(f"  {doc}:{lineno}: {line}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
